"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = __importDefault(require("express"));
const cors_1 = __importDefault(require("cors"));
const connection_1 = __importDefault(require("./connection"));
const dotenv_1 = __importDefault(require("dotenv"));
dotenv_1.default.config();
const app = (0, express_1.default)();
const { PORT } = process.env;
(0, connection_1.default)();
app.use((0, cors_1.default)());
app.use(express_1.default.json());
app.use(express_1.default.static("pfp"));
app.use(express_1.default.static("public"));
app.use("/users", require("./controllers/users"));
app.use("/songs", require("./controllers/songs"));
app.use("/playlists", require("./controllers/playlists"));
app.use("/likes", require("./controllers/likes"));
app.listen(PORT, () => console.log(`App is running on PORT: ${PORT}`));
